spring.application.name=codetracker

spring.datasource.url=jdbc:mysql://localhost:3306/codetracker_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Changed default application port from 8081 to 8080 to avoid conflicts
server.port=8080

# JWT Configuration
jwt.secret=mySecretKeyForJWTAuthenticationAndAuthorizationPurposesOnlyNotForProductionUse
jwt.expiration=86400000

spring.sql.init.mode=always